### ISSUE TITLE
nanoid is not a function

### ISSUE THREAD

**Issue by morozovkirill** [felixfbecker/dom-to-svg#176]
Hello.
First of all, thanks for library. It's very helpfull.

But I have this error in console:
<img width="635" alt="Снимок экрана 2022-06-17 в 12 50 05" src="https://user-images.githubusercontent.com/22151111/174274848-302696c1-3de6-4fff-8990-c08292d2bb07.png">

It seems, some troubles with nanoid import. Here is issue - [https://github.com/ai/nanoid/issues/205](https://github.com/ai/nanoid/issues/205)

Any ideas, how to fix it?

**Comment by morozovkirill** [comment]
fixed it with new version react-scripts

**Comment by f4z3k4s** [comment]
@morozovkirill how did you fix it exactly? I am on latest react-scripts (5.0.1) and still get this error. Regardless, export seems to work fine.

**Comment by iashris** [comment]
I'm also having the same issue! Using the latest version of react-scripts (5.0.1) and still get this error.
